insert into categorie(nom) VALUES
('film'),
('série'),
('jeu vidéo'),
('livre audio'),
('voix-off'),
('animation'),
('série animée')
;

insert into oeuvre(nom, parution, photo, categorie_id) VALUES
('Resident Evil 4 Remake', '2023-03-06', null, 3),
('Game of thrones', '2023-03-06', null, 2),
('LadyBug', '2020-01-06', null, 7),
('Mario Bros Le Film', '2023-04-06', null, 6),
('Pirates des Caraïbes', '2018-03-06', null, 1),
('Roi Lion', '1998-11-24', null, 6),
('Aladdin', '1998-03-06', null, 6)
;

insert into jouer(oeuvre_id, comedien_id, role, vf, vo) VALUES
(1, 10, 'Leon S Kennedy', true, false),
(1, 3, 'Ashley Graham', true, false),
(1, 11, 'Salazar', true, false),
(4, 23, 'Mario', true, false),
(4, 24, 'Peach', true, false),
(4, 31, 'Luigi', true, false),
--(4, 27, Bowser, true, false),
(6, 40, 'Simba Adulte', true, false),
(6, 7, 'Pumba', true, false),
(7, 7, 'Caverne en Merveilles', true, false),
(7, 13, 'Jafar', true, false)
;

insert into comedien(nom, prenom, da, photo) VALUES 
('Saez', 'Marc', true, null), 
('Souterelle', 'Frédéric', true, null), 
('Nonenmacher', 'Marie', true, null), 
('Reignoux', 'Donald', true, null), 
('Poivey', 'Patrick', false, null), 
('Béthune', 'Patrick', false, null), 
('Elias', 'Michel', false, null), 
('Volpe', 'Isabelle', false, null), 
('Diot', 'Marie', false, null), 
('De Bodinat', 'Anatole', false, null), 
('Ronchewski', 'Stéphane', false, null), 
('Michael', 'Jean-Pierre', true, null), 
('Atkine', 'Féodor', true, null),
('Allemane', 'Benoît', false, null),
('Luccioni', 'José', true, null),
('Luccioni', 'Olivia', true, null),
('Rehlinger', 'Boris', false, null),
('Asselin', 'Géraldine', true, null),
('Krüger', 'David', false, null),
('Lebfevre', 'Läetitia', false, null),
('Karsenti', 'Nathalie', false, null),
('Victor', 'Alexis', false, null),
('Teissier', 'Pierre', false, null),
('Sourdive', 'Audrey', false, null),
('Nguyen', 'Alexandre', false, null),
('Le Minoux', 'Martial', true, null),
('Covillaut', 'Jeremy', false, null),
('Antoine', 'Adrien', false, null),
('Morvan', 'Gilles', true, null),
('Orsat', 'Guillaume', true, null),
('Du Pac', 'Benoît', true, null),
('Desroses', 'Thierry', false, null),
('Donnadieu', 'Ingrid', false, null),
('Pauwels', 'Jerôme', true, null),
('Marot', 'Kelly', false, null),
('Soarez', 'Clara', false, null),
('Bloc', 'Fanny', false, null),
('Levy', 'Gilbert', true, null),
('Combes', 'Caroline', false, null),
('Curtil', 'Emmanuel', false, null),
('Tissier', 'Barbara', true, null),
('De Guarrigues', 'Pierre-Alain', false, null),
('Violette', 'Vincent', true, null),
('Monsarrat', 'Céline', true, null),
('Meyere', 'Bruno', true, null),
('Gradi', 'Emmanuel', false, null),
('Brière', 'Jean-Philippe', false, null),
('Chetail', 'Adeline', false, null),
('Beretta', 'Daniel', false, null),
('Beretta', 'Barbara', false, null),
('Dégenne', 'Juliette', false, null),
('Borne', 'Paul', false, null),
('Peythieu', 'Philippe', true, null),
('Augereau', 'Véronique', true, null)
;